server:
  port: ${SERVER_PORT:18761}
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    expected-client-renewal-interval-seconds: 10
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO

