set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT/infrastructure/docker/.env}"
OUT_DIR="${OUT_DIR:-$ROOT/.run}"
OUT_FILE="$OUT_DIR/ports.env"

if [[ -f "$ENV_FILE" ]]; then
  set -a
  source "$ENV_FILE"
  set +a
fi

mkdir -p "$OUT_DIR"

if [[ -f "$OUT_FILE" && "${ALLOCATE_FORCE:-0}" != "1" ]]; then
  echo "reusing $OUT_FILE (ALLOCATE_FORCE=1 make ports to reallocate)" >&2
  exit 0
fi

port_in_use() {
  local port="$1"
  if command -v lsof >/dev/null 2>&1; then
    lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1
    return $?
  fi
  # Fallback when lsof is missing (rare on macOS).
  nc -z 127.0.0.1 "$port" >/dev/null 2>&1
}

pick_port() {
  local preferred="$1"
  local label="$2"
  local candidate="$preferred"
  local i=0
  while port_in_use "$candidate"; do
    i=$((i + 1))
    if [[ "$i" -gt 80 ]]; then
      echo "error: no free port near $preferred for $label" >&2
      exit 1
    fi
    candidate=$((preferred + i))
  done
  if [[ "$candidate" -ne "$preferred" ]]; then
    echo "  $label: $preferred busy → $candidate" >&2
  else
    echo "  $label: $candidate" >&2
  fi
  echo "$candidate"
}

echo "allocating Tennisly ports…" >&2

POSTGRES_PORT="$(pick_port "${POSTGRES_PORT:-15432}" postgres)"
REDIS_PORT="$(pick_port "${REDIS_PORT:-16379}" redis)"
KAFKA_EXTERNAL_PORT="$(pick_port "${KAFKA_EXTERNAL_PORT:-19094}" kafka)"
MINIO_API_PORT="$(pick_port "${MINIO_API_PORT:-19000}" minio-api)"
MINIO_CONSOLE_PORT="$(pick_port "${MINIO_CONSOLE_PORT:-19001}" minio-console)"
EUREKA_SERVER_PORT="$(pick_port "${EUREKA_SERVER_PORT:-18761}" eureka)"
TENNIS_DATA_SERVER_PORT="$(pick_port "${TENNIS_DATA_SERVER_PORT:-18083}" tennis-data)"
MATCH_SERVER_PORT="$(pick_port "${MATCH_SERVER_PORT:-18084}" match)"
REPLAY_SERVER_PORT="$(pick_port "${REPLAY_SERVER_PORT:-18085}" replay)"
WEB_PORT="$(pick_port "${WEB_PORT:-13000}" web)"
PGADMIN_PORT="$(pick_port "${PGADMIN_PORT:-15050}" pgadmin)"
REDIS_COMMANDER_PORT="$(pick_port "${REDIS_COMMANDER_PORT:-18081}" redis-commander)"
KAFKA_UI_PORT="$(pick_port "${KAFKA_UI_PORT:-18082}" kafka-ui)"
ELASTICSEARCH_PORT="$(pick_port "${ELASTICSEARCH_PORT:-19200}" elasticsearch)"

cat >"$OUT_FILE" <<EOF
# Generated by scripts/allocate-ports.sh — do not commit.
POSTGRES_PORT=$POSTGRES_PORT
REDIS_PORT=$REDIS_PORT
KAFKA_EXTERNAL_PORT=$KAFKA_EXTERNAL_PORT
MINIO_API_PORT=$MINIO_API_PORT
MINIO_CONSOLE_PORT=$MINIO_CONSOLE_PORT
EUREKA_SERVER_PORT=$EUREKA_SERVER_PORT
TENNIS_DATA_SERVER_PORT=$TENNIS_DATA_SERVER_PORT
MATCH_SERVER_PORT=$MATCH_SERVER_PORT
REPLAY_SERVER_PORT=$REPLAY_SERVER_PORT
WEB_PORT=$WEB_PORT
PGADMIN_PORT=$PGADMIN_PORT
REDIS_COMMANDER_PORT=$REDIS_COMMANDER_PORT
KAFKA_UI_PORT=$KAFKA_UI_PORT
ELASTICSEARCH_PORT=$ELASTICSEARCH_PORT
KAFKA_BOOTSTRAP_SERVERS=localhost:$KAFKA_EXTERNAL_PORT
EUREKA_URI=http://localhost:$EUREKA_SERVER_PORT/eureka
TENNIS_DATA_SERVICE_URI=http://localhost:$TENNIS_DATA_SERVER_PORT
REPLAY_MATCH_SERVICE_URI=http://localhost:$MATCH_SERVER_PORT
REPLAY_TENNIS_DATA_SERVICE_URI=http://localhost:$TENNIS_DATA_SERVER_PORT
REPLAY_STORAGE_ENDPOINT=http://localhost:$MINIO_API_PORT
MATCH_SERVICE_URL=http://localhost:$MATCH_SERVER_PORT
TENNIS_DATA_SERVICE_URL=http://localhost:$TENNIS_DATA_SERVER_PORT
REPLAY_SERVICE_URL=http://localhost:$REPLAY_SERVER_PORT
PORT=$WEB_PORT
EOF

echo "wrote $OUT_FILE" >&2
